// ============================================================
// RINK Technology Explorer — Google Sheets Data Layer
//
// Fetches live data from the Google Sheets CSV export.
// Uses Next.js ISR (revalidate: 300 = 5 minutes) so new
// rows in the sheet appear automatically without redeploy.
//
// Sheet URL:
// https://docs.google.com/spreadsheets/d/1HXlzT504-AhqzfU6Nm3bktAspIjaQm2l1z45qROZrFc
// ============================================================

import { Technology, Sector, Institution, StartupPotential } from '@/types';

const SHEET_ID = '1HXlzT504-AhqzfU6Nm3bktAspIjaQm2l1z45qROZrFc';
const SHEET_CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=0`;

// ── Sector metadata (color only — icons are SVGs in SectorIcons.tsx) ──────
// Keys are slugs generated by toSlug() from the sector name in Google Sheet
const SECTOR_META: Record<string, { icon: string; color: string }> = {
  // ── New consolidated 12 sectors ──────────────────────────────
  'agriculture':                                    { icon: '🌾', color: '#16a34a' },
  'biotechnology-life-sciences':                    { icon: '🔬', color: '#7c3aed' },
  'biotechnology-life-sciences-1':                  { icon: '🔬', color: '#7c3aed' },
  'food-technology':                                { icon: '🍽️', color: '#ea580c' },
  'advanced-materials-chemicals':                   { icon: '⚗️', color: '#9333ea' },
  'medtech-health-care':                            { icon: '🏥', color: '#be185d' },
  'robotics-automation-drones':                     { icon: '🤖', color: '#4f46e5' },
  'infrastructure-construction-smart-cities':       { icon: '🏗️', color: '#b45309' },
  'digital-technologies-al-software':              { icon: '💻', color: '#0891b2' },
  'digital-technologies-ai-software':              { icon: '💻', color: '#0891b2' },
  'manufacturing-industrial-technologies':          { icon: '⚙️', color: '#dc2626' },
  'consumer-products-cosmetics-lifestyle':          { icon: '🛍️', color: '#db2777' },
  'energy-climate-sustainability':                  { icon: '⚡', color: '#ca8a04' },
  'water-environment-waste-management':             { icon: '💧', color: '#2563eb' },

  // ── Legacy / old sector slugs (fallback for any remaining old data) ──
  'food-processing':         { icon: '🍽️', color: '#ea580c' },
  'biotechnology':           { icon: '🔬', color: '#7c3aed' },
  'aquaculture':             { icon: '🐟', color: '#0284c7' },
  'environment':             { icon: '🌿', color: '#15803d' },
  'materials':               { icon: '⚗️', color: '#9333ea' },
  'construction':            { icon: '🏗️', color: '#b45309' },
  'agritech':                { icon: '📡', color: '#0d9488' },
  'post-harvest':            { icon: '📦', color: '#d97706' },
  'water-technology':        { icon: '💧', color: '#2563eb' },
  'renewable-energy':        { icon: '⚡', color: '#ca8a04' },
  'climate-tech':            { icon: '🌱', color: '#65a30d' },
  'manufacturing':           { icon: '⚙️', color: '#dc2626' },
  'sustainable-materials':   { icon: '♻️', color: '#059669' },
  'healthcare':              { icon: '🏥', color: '#be185d' },
  'smart-systems':           { icon: '🤖', color: '#4f46e5' },
  'transportation':          { icon: '🚗', color: '#0369a1' },
  'ict':                     { icon: '💻', color: '#0891b2' },
  'energy':                  { icon: '⚡', color: '#ca8a04' },
  'sustainability':          { icon: '🌱', color: '#059669' },
  'cosmetics':               { icon: '🛍️', color: '#db2777' },
  'electronics':             { icon: '💡', color: '#4f46e5' },
  'electronics-and-communication': { icon: '📡', color: '#0891b2' },
  'chemical-sciences':       { icon: '⚗️', color: '#9333ea' },
  'food-processing-iot':     { icon: '🍽️', color: '#ea580c' },
  'food-processing-food-technology': { icon: '🍽️', color: '#ea580c' },
  'sector':                  { icon: '🔧', color: '#6b7280' },
  'default':                 { icon: '🔧', color: '#6b7280' },
};


// ── Slug helpers ─────────────────────────────────────────────
export function toSlug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

function getSectorMeta(slug: string) {
  return SECTOR_META[slug] ?? SECTOR_META['default'];
}

// ── Google Drive URL converter ────────────────────────────────
// Converts any Drive share link into a direct thumbnail URL that
// works in <img> tags without redirects or consent prompts.
// Drive thumbnail endpoint: https://drive.google.com/thumbnail?id=FILE_ID&sz=w800
export function toDriveEmbedUrl(url: string): string {
  if (!url || url === 'Not Specified' || url === 'NA' || url.trim() === '') return '';

  const trimmed = url.trim();

  // Already a thumbnail URL — return as-is
  if (trimmed.includes('drive.google.com/thumbnail')) return trimmed;

  // Already a uc?export=view URL — convert to thumbnail for reliability
  if (trimmed.includes('drive.google.com/uc?')) {
    const idMatch = trimmed.match(/[?&]id=([^&]+)/);
    if (idMatch) return `https://drive.google.com/thumbnail?id=${idMatch[1]}&sz=w800`;
    return trimmed;
  }

  // Pattern: https://drive.google.com/file/d/FILE_ID/view?...
  const fileMatch = trimmed.match(/\/file\/d\/([a-zA-Z0-9_-]+)/);
  if (fileMatch) {
    return `https://drive.google.com/thumbnail?id=${fileMatch[1]}&sz=w800`;
  }

  // Pattern: https://drive.google.com/open?id=FILE_ID
  const openMatch = trimmed.match(/[?&]id=([a-zA-Z0-9_-]+)/);
  if (openMatch) {
    return `https://drive.google.com/thumbnail?id=${openMatch[1]}&sz=w800`;
  }

  // Pattern: https://drive.google.com/drive/folders/... (not an image — skip)
  if (trimmed.includes('drive.google.com/drive/')) return '';

  // Non-Drive URL — return as-is (might be a direct image link)
  return trimmed;
}

// ── Startup potential mapping ─────────────────────────────────
function potentialScore(level: string): number {
  const l = level.toLowerCase();
  if (l === 'featured') return 10;
  if (l === 'very high') return 8;
  if (l === 'high') return 5;
  if (l === 'medium') return 3;
  if (l === 'low') return 2;
  return 1;
}

// ── CSV Parser (handles quoted multi-line fields) ─────────────
function parseCSV(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuotes = false;
  let i = 0;

  while (i < text.length) {
    const ch = text[i];

    if (ch === '"') {
      if (inQuotes && text[i + 1] === '"') {
        // Escaped quote
        field += '"';
        i += 2;
        continue;
      }
      inQuotes = !inQuotes;
      i++;
      continue;
    }

    if (ch === ',' && !inQuotes) {
      row.push(field.trim());
      field = '';
      i++;
      continue;
    }

    if ((ch === '\r' || ch === '\n') && !inQuotes) {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(field.trim());
      if (row.some(f => f !== '')) rows.push(row);
      row = [];
      field = '';
      i++;
      continue;
    }

    field += ch;
    i++;
  }

  // Last field
  if (field.trim() || row.length > 0) {
    row.push(field.trim());
    if (row.some(f => f !== '')) rows.push(row);
  }

  return rows;
}

// ── Row → Technology ──────────────────────────────────────────
// Sheet columns (0-indexed):
// 0: Technology ID
// 1: Technology Name
// 2: Institution
// 3: Sector
// 4: Technology Type
// 5: Problem Solved
// 6: Description
// 7: Applications
// 8: Startup Potential
// 9: TRL
// 10: Patent Status
// 11: Contact Person
// 12: Phone
// 13: Email
// 14: Source PDF (ignore)
// 15: Page No (ignore)
// 16: Keywords
// 17: Image URL
// 18: Institution Website

function getHeaderMap(headers: string[]): Record<string, number> {
  const map: Record<string, number> = {};
  headers.forEach((h, idx) => {
    const cleanHeader = h.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    map[cleanHeader] = idx;
  });
  return map;
}

function rowToTechnology(row: string[], headerMap: Record<string, number>): Technology | null {
  const getVal = (keys: string[], fallback: string = ''): string => {
    for (const key of keys) {
      const idx = headerMap[key];
      if (idx !== undefined && row[idx] !== undefined && row[idx] !== '') {
        return row[idx].trim();
      }
    }
    return fallback;
  };

  const id = getVal(['technologyid', 'id']);
  const name = getVal(['technologyname', 'name']);

  if (!id || !name || id === 'Technology ID') return null;

  const institution = getVal(['institution']) || 'Unknown Institution';
  const sector = getVal(['sector']) || 'General';
  
  const phone = getVal(['phone', 'contactno', 'contactphone', 'mobile'], '')
    .replace(/[\r\n]+/g, '')
    .trim();
  const email = getVal(['email', 'contactemail']);
  const imageUrl = getVal(['imageurl', 'image', 'photourl', 'embedurl', 'imagelink', 'imgurl']);

  // Log missing image URLs in development to help debug
  if (process.env.NODE_ENV === 'development' && !imageUrl) {
    console.warn(`[RINK] No image URL for tech: ${id} — "${name}"`);
  }
  const startupPotentialRaw = getVal(['startuppotential', 'potential'], 'Not Specified') as StartupPotential;

  const keywordsRaw = getVal(['keywords', 'tags']);
  const keywords = keywordsRaw
    ? keywordsRaw.split(/[,;]/).map(k => k.trim()).filter(Boolean)
    : [];

  const applicationsRaw = getVal(['applications', 'usecases']);
  const applications = applicationsRaw
    ? applicationsRaw
        .split(/[\n\r]+|[,;]/)
        .map(a => a.trim())
        .filter(a => a.length > 0)
    : [];

  const sectorSlug = toSlug(sector);
  const institutionSlug = toSlug(institution);
  const embedUrl = toDriveEmbedUrl(imageUrl);

  const trlVal = getVal(['trl', 'trllevel']);
  const trl = trlVal && trlVal !== 'Not Specified' && trlVal !== 'NA' ? trlVal : 'TRL Not Available';

  const patentVal = getVal(['patentstatus', 'patent']);
  const patent_status = patentVal && patentVal !== 'Not Specified' && patentVal !== 'NA' ? patentVal : 'Patent Status Not Available';

  const commVal = getVal(['commercializationstatus', 'commercialization', 'status']);
  const commercialization_status = commVal && commVal !== 'Not Specified' && commVal !== 'NA' ? commVal : 'Commercialization Status Not Available';

  const techImage = getVal(['technologyimage', 'technologyphotourl', 'techimage', 'technologyimageurl']);
  const instImage = getVal(['institutionimage', 'institutionlogo', 'logo', 'institutionlogourl', 'institutionlogo']);
  const lastUpdated = getVal(['lastupdated', 'updated', 'lastupdateddate']);

  // Log resolved image URLs in development
  if (process.env.NODE_ENV === 'development' && (imageUrl || techImage)) {
    const resolvedUrl = imageUrl ? toDriveEmbedUrl(imageUrl) : (techImage ? toDriveEmbedUrl(techImage) : '');
    console.log(`[RINK] Image for "${name}": raw=${imageUrl || techImage}, resolved=${resolvedUrl}`);
  }

  const techImageEmbedUrl = techImage ? toDriveEmbedUrl(techImage) : '';
  const instImageEmbedUrl = instImage ? toDriveEmbedUrl(instImage) : '';

  return {
    id,
    name,
    institution,
    institution_slug: institutionSlug,
    sector,
    sector_slug: sectorSlug,
    technology_type: getVal(['technologytype', 'type'], 'Not Specified'),
    problem_solved: getVal(['problemsolved', 'problem'], 'Information being updated'),
    description: getVal(['description', 'desc'], 'Information being updated'),
    applications: applications.length ? applications : ['Information being updated'],
    startup_potential: startupPotentialRaw,
    startup_potential_score: potentialScore(startupPotentialRaw),
    trl,
    patent_status,
    commercialization_status,
    contact_person: getVal(['contactperson', 'contact'], 'Contact Institution'),
    phone,
    email,
    keywords,
    image_url: imageUrl,
    image_embed_url: embedUrl,
    institution_website: getVal(['institutionwebsite', 'website', 'url']),
    featured: ['featured', 'very high', 'high'].includes(startupPotentialRaw.toLowerCase()),
    technology_image: techImage,
    technology_image_embed_url: techImageEmbedUrl,
    institution_image: instImage,
    institution_image_embed_url: instImageEmbedUrl,
    last_updated: lastUpdated
  };
}

// ── Main fetch function ───────────────────────────────────────
let _cache: { data: Technology[]; ts: number } | null = null;

// Dev mode: no cache (always live from sheet)
// Production: 5-minute cache to reduce API calls
const CACHE_TTL = process.env.NODE_ENV === 'development'
  ? 0                  // instant refresh in dev
  : 60 * 1000;         // 1 minute in production

// Call this to force-clear the cache (used by /api/revalidate)
export function clearCache() {
  _cache = null;
  console.log('[RINK] Cache cleared — next request will fetch fresh sheet data');
}

export async function fetchAllTechnologies(): Promise<Technology[]> {
  // In-memory cache check (0ms TTL in dev = always bypass)
  if (_cache && Date.now() - _cache.ts < CACHE_TTL) {
    return _cache.data;
  }

  // In dev: cache:'no-store' forces a fresh HTTP request every time
  // In prod: revalidate every 1 minute via Next.js ISR
  const fetchOptions: RequestInit =
    process.env.NODE_ENV === 'development'
      ? { cache: 'no-store' }                 // always fresh in dev
      : { next: { revalidate: 60 } } as RequestInit; // 1-min ISR in prod

  try {
    const res = await fetch(SHEET_CSV_URL, fetchOptions);

    if (!res.ok) {
      console.error(`[RINK] Sheet fetch failed: ${res.status}`);
      return [];
    }

    const text = await res.text();
    const rows = parseCSV(text);

    if (rows.length === 0) return [];

    const headerRow = rows[0];
    const headerMap = getHeaderMap(headerRow);

    // Skip header row
    const technologies: Technology[] = [];
    for (let i = 1; i < rows.length; i++) {
      const tech = rowToTechnology(rows[i], headerMap);
      if (tech) technologies.push(tech);
    }

    _cache = { data: technologies, ts: Date.now() };
    console.log(`[RINK] Loaded ${technologies.length} technologies from Google Sheets`);
    return technologies;
  } catch (err) {
    console.error('[RINK] Failed to fetch sheet data:', err);
    return _cache?.data ?? [];
  }
}


// ── Derived data helpers ──────────────────────────────────────

export async function fetchSectors(): Promise<Sector[]> {
  const techs = await fetchAllTechnologies();
  const map = new Map<string, { name: string; count: number }>();

  for (const t of techs) {
    const existing = map.get(t.sector_slug);
    if (existing) {
      existing.count++;
    } else {
      map.set(t.sector_slug, { name: t.sector, count: 1 });
    }
  }

  return Array.from(map.entries())
    .map(([slug, { name, count }]) => ({
      slug,
      name,
      tech_count: count,
      ...getSectorMeta(slug),
    }))
    .sort((a, b) => b.tech_count - a.tech_count);
}

export async function fetchInstitutions(): Promise<Institution[]> {
  const techs = await fetchAllTechnologies();
  const map = new Map<string, { name: string; count: number; image?: string; imageEmbed?: string; lastUpdated?: string }>();

  for (const t of techs) {
    const existing = map.get(t.institution_slug);
    if (existing) {
      existing.count++;
      if (!existing.image && t.institution_image) {
        existing.image = t.institution_image;
        existing.imageEmbed = t.institution_image_embed_url;
      }
      if (!existing.lastUpdated && t.last_updated) {
        existing.lastUpdated = t.last_updated;
      }
    } else {
      map.set(t.institution_slug, {
        name: t.institution,
        count: 1,
        image: t.institution_image,
        imageEmbed: t.institution_image_embed_url,
        lastUpdated: t.last_updated
      });
    }
  }

  return Array.from(map.entries())
    .map(([slug, { name, count, image, imageEmbed, lastUpdated }]) => ({
      slug,
      name,
      tech_count: count,
      institution_image: image,
      institution_image_embed_url: imageEmbed,
      last_updated: lastUpdated
    }))
    .sort((a, b) => b.tech_count - a.tech_count);
}


// ── Institution Details Sheet ─────────────────────────────────
// Fetches structured institution information from a dedicated tab
// (gid=1979443544) and merges with technology counts from the main sheet.

const INSTITUTION_DETAILS_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=1979443544`;

interface InstitutionDetailRow {
  name: string;
  slug: string;
  logo_url: string;
  logo_embed_url: string;
  address: string;
  website: string;
  contact_email: string;
  contact_phone: string;
}

let _instDetailsCache: { data: InstitutionDetailRow[]; ts: number } | null = null;

export async function fetchInstitutionDetails(): Promise<InstitutionDetailRow[]> {
  if (_instDetailsCache && Date.now() - _instDetailsCache.ts < CACHE_TTL) {
    return _instDetailsCache.data;
  }

  const fetchOptions: RequestInit =
    process.env.NODE_ENV === 'development'
      ? { cache: 'no-store' }
      : { next: { revalidate: 60 } } as RequestInit;

  try {
    const res = await fetch(INSTITUTION_DETAILS_URL, fetchOptions);
    if (!res.ok) {
      console.error(`[RINK] Institution Details sheet fetch failed: ${res.status}`);
      return _instDetailsCache?.data ?? [];
    }

    const text = await res.text();
    const rows = parseCSV(text);
    if (rows.length === 0) return [];

    const headerMap = getHeaderMap(rows[0]);
    const details: InstitutionDetailRow[] = [];

    for (let i = 1; i < rows.length; i++) {
      const row = rows[i];
      const getVal = (keys: string[], fallback = ''): string => {
        for (const key of keys) {
          const idx = headerMap[key];
          if (idx !== undefined && row[idx] !== undefined && row[idx].trim() !== '') {
            return row[idx].trim();
          }
        }
        return fallback;
      };

      const name = getVal(['institutionname', 'name', 'institution']);
      if (!name) continue;

      const logoRaw = getVal(['institutionlogourl', 'institutionlogo', 'logo', 'logourl', 'institutionimage', 'image']);
      const logoEmbed = toDriveEmbedUrl(logoRaw);

      details.push({
        name,
        slug: toSlug(name),
        logo_url: logoRaw,
        logo_embed_url: logoEmbed,
        address: getVal(['address', 'location', 'institutionaddress']),
        website: getVal(['locationwebsitelink', 'website', 'officialwebsite', 'url', 'institutionwebsite']),
        contact_email: getVal(['email', 'contactemail']),
        contact_phone: getVal(['phone', 'contactphone']),
      });
    }

    _instDetailsCache = { data: details, ts: Date.now() };
    console.log(`[RINK] Loaded ${details.length} institution details from sheet`);
    return details;
  } catch (err) {
    console.error('[RINK] Failed to fetch institution details:', err);
    return _instDetailsCache?.data ?? [];
  }
}

// ── Merged institution data (Details + Technology counts) ─────
export async function fetchMergedInstitutions(): Promise<Institution[]> {
  const [techs, details] = await Promise.all([
    fetchAllTechnologies(),
    fetchInstitutionDetails(),
  ]);

  // Build tech count map from main sheet
  const countMap = new Map<string, { name: string; count: number; image?: string; imageEmbed?: string }>();
  for (const t of techs) {
    const existing = countMap.get(t.institution_slug);
    if (existing) {
      existing.count++;
    } else {
      countMap.set(t.institution_slug, {
        name: t.institution,
        count: 1,
        image: t.institution_image,
        imageEmbed: t.institution_image_embed_url,
      });
    }
  }

  // Build details lookup by slug (also index by partial slug for fuzzy matching)
  const detailsMap = new Map<string, InstitutionDetailRow>();
  for (const d of details) {
    detailsMap.set(d.slug, d);
  }

  // Fuzzy match: if exact slug doesn't match, try finding a detail whose slug is contained in or contains the tech slug
  function findDetail(slug: string): InstitutionDetailRow | undefined {
    const exact = detailsMap.get(slug);
    if (exact) return exact;
    for (const [dSlug, d] of detailsMap.entries()) {
      if (slug.includes(dSlug) || dSlug.includes(slug)) return d;
    }
    return undefined;
  }

  // Merge: start from countMap (ensures every institution with technologies is included)
  const merged: Institution[] = [];
  for (const [slug, info] of countMap.entries()) {
    const detail = findDetail(slug);
    merged.push({
      slug,
      name: detail?.name || info.name,
      tech_count: info.count,
      institution_image: detail?.logo_url || info.image,
      institution_image_embed_url: detail?.logo_embed_url || info.imageEmbed,
      logo_url: detail?.logo_url,
      logo_embed_url: detail?.logo_embed_url,
      address: detail?.address,
      website: detail?.website,
      contact_email: detail?.contact_email,
      contact_phone: detail?.contact_phone,
    });
  }

  // Also include institutions from details that have no technologies yet
  for (const d of details) {
    if (!countMap.has(d.slug)) {
      merged.push({
        slug: d.slug,
        name: d.name,
        tech_count: 0,
        logo_url: d.logo_url,
        logo_embed_url: d.logo_embed_url,
        institution_image: d.logo_url,
        institution_image_embed_url: d.logo_embed_url,
        address: d.address,
        website: d.website,
        contact_email: d.contact_email,
        contact_phone: d.contact_phone,
      });
    }
  }

  return merged.sort((a, b) => b.tech_count - a.tech_count);
}
